language: python
python:
  - "3.6"
before_install:
  - make lint
script:
  - make test
after_success:
  # Report test coverage
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
